### PR TITLE
attempt at new function

### PR DESCRIPTION
**Pull request by dusty-turner**
Ben, as a part of a project I'm doing, I dug around in the API and pulled out a lot more information about the requested rider.  I created a different function for it (instead of replacing your function).  I used a little different coding style than you and I specified all the outputs from each level of the json.  I also understand you may find this a little sloppy and understand if you'd rather not merge it in.  Please feel free to reject or recode it to your style.  This is also really my first attempt at roxygen so I hope it all works appropriately.  If you'd rather email about this offline instead of on github, please feel to reach out to me at dusty.s.turner@gmail.com.  Thanks!

### CODE REVIEW

**Comment by bweiher** [comment]
Thanks Dusty!  

This is another very helpful PR! I did not know about `purr::pluck` or the join thingy w/ the Peloton APIs to get additional data, that is quite helpful. 

I understand the use of `pluck` here, but I'm wondering if there is a slightly different approach we could take. 

Originally I made the `parse_list_to_df` function since I didn’t want to accidentally drop anything someone might find useful. That works pretty well for the first tier of the JSON, but I didn’t consider something like the `joins=ride` param that appears to create a new list-column, which adds a lot of overhead for the user to get what they need. I tried out a slightly different approach in my [PR](https://github.com/bweiher/pelotonR/pull/6) , wondering if you could give it a :eye: . You can basically supply the join-params as an additional function argument and then the additional information is added as additional columns prefixed with `rides_` .

I think your approach of using `pluck` makes a lot of sense, but for consistency sake I think it makes sense to rely on a single paved path. I'm thinking of trying to get this on CRAN and not sure if design choices like that will become an issue one day or not. LMK your thoughts // if you get a chance to try it out. I gave it a little bit of testing and it seems to mostly work, but open to revisiting this if you have any additional comments or context! 

 I really appreciate your continued effort making this package more useful!

**Comment by dusty-turner** [comment]
Ben, so sorry for my delay here.  These alerts get filtered in my gmail and I'm just now realizing you responded here.

I appreciate the note and I'll look it over (hopefully this weekend). I certainly think having a consistently styled code makes sense for many reasons.  I like the idea of it being on CRAN to and I'm happy to help if you like and I'll see if there's any other useful functionality I can think of.

Thanks!

**Comment by dusty-turner** [comment]
Ben, again I apologize for being so slow in getting back to this.  I really like the versatility of your code. Really well done -- and I agree with keeping the single paved path of style.  I'm going to spend some time this weekend (I think) trying to build out a blog post on some of my rides and highlight your package (if you don't mind me doing it).  I'll put another comment or PR if I come across something worthwhile.

**Comment by bweiher** [comment]
closing this pr @dusty-turner  thanks!

**Pull request closed without merging**
